name: actionlint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/*.yml
  schedule:
    - cron: '0 11 * * *' # Run nightly at 11am UTC (3am Pacific, 6am Eastern)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
    run:
      shell: bash

jobs:
  actionlint:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false
          sparse-checkout: '.github/'
      - name: actionlint
        uses: docker://index.docker.io/rhysd/actionlint@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9 # ratchet:docker://rhysd/actionlint:1.7.7
        with:
          args: -color .github/workflows/actionlint.yml .github/workflows/build.yml .github/workflows/spotless.yml
