name: spotless

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/spotless.yml
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.md'
  schedule:
    - cron: '0 11 * * *' # Run nightly at 11am UTC (3am Pacific, 6am Eastern)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
    run:
      shell: bash

jobs:
  check:
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: temurin

      - name: Restore Gradle Cache
        uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # 4.2.2
        if: github.event_name != 'schedule'
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-achxw8vq63-${{ github.run_id }}
          restore-keys: |
            gradle-cache-achxw8vq63-

      - name: spotlessCheck
        run: ./gradlew --warning-mode all spotlessCheck

      - name: Save Gradle Cache
        uses: actions/cache/save@d4323d4df104b026a6aa633fdb11d772146be0bf # 4.2.2
        if: github.event_name == 'schedule'
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-achxw8vq63-${{ github.run_id }}
